(()=>{
'use strict';
const C=window.NEMS_MAINT_CONFIG||{};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=v=>{if(!v)return '—';const d=new Date(v+'T00:00:00');return isNaN(d)?v:d.toLocaleDateString('vi-VN')};
let session=JSON.parse(localStorage.getItem('nemsMaintSession')||'null');
let plans=[],workorders=[],mhistory=[],users=[];
let equipment=[];

window.NEMS_READY.then(D=>{equipment=D.equipment||[]; boot();});

async function api(action,payload={}){
 if(!C.apiUrl) throw new Error('Chưa cấu hình URL Apps Script.');
 const body={action,...payload}; if(session?.token) body.token=session.token;
 const r=await fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),redirect:'follow'});
 const t=await r.text(); let j; try{j=JSON.parse(t)}catch{throw new Error('API trả về dữ liệu không hợp lệ. Kiểm tra quyền triển khai Web App.');}
 if(!j.ok) throw new Error(j.error||'Lỗi API'); return j;
}
function boot(){
 bindTabs(); bindButtons(); updateRoleUI();
 if(session) refreshAll().catch(e=>{toast(e.message); logout(false)});
 const obs=new MutationObserver(()=>loadAssetMaintenance()); const el=$('#detailAsset'); if(el)obs.observe(el,{childList:true,subtree:true});
}
function bindTabs(){
 $$('.maint-tab').forEach(b=>b.onclick=()=>{ $$('.maint-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.maint-pane').forEach(x=>x.classList.add('hidden'));$('#maint-'+b.dataset.maintTab)?.classList.remove('hidden');});
}
function bindButtons(){
 $('#maintLoginBtn').onclick=loginDialog; $('#maintLogoutBtn').onclick=()=>logout(true);
 $('#newPlanBtn').onclick=()=>planDialog(); $('#newWoBtn').onclick=()=>woDialog(); $('#newHistoryBtn').onclick=()=>historyDialog(); $('#newUserBtn').onclick=()=>userDialog();
 $('#planSearch').oninput=renderPlans; $('#planStatusFilter').onchange=renderPlans;
 $('#maintModalClose').onclick=closeModal; $('#maintModal').addEventListener('click',e=>{if(e.target.id==='maintModal')closeModal()});
}
function updateRoleUI(){
 const role=session?.role||''; $('#maintUserLabel').textContent=session?`${session.fullName||session.username} · ${role}`:'Chưa đăng nhập';
 $('#maintLoginBtn').classList.toggle('hidden',!!session);$('#maintLogoutBtn').classList.toggle('hidden',!session);
 $$('.editor-only').forEach(x=>x.classList.toggle('hidden',!['admin','technician'].includes(role)));
 $$('.admin-only').forEach(x=>x.classList.toggle('hidden',role!=='admin'));
}
function modal(title,html,onSubmit){$('#maintModalTitle').textContent=title;$('#maintForm').innerHTML=html;$('#maintModal').classList.remove('hidden');$('#maintForm').onsubmit=async e=>{e.preventDefault();const btn=$('#maintForm button[type=submit]');if(btn)btn.disabled=true;try{await onSubmit(new FormData(e.target));closeModal()}catch(err){alert(err.message)}finally{if(btn)btn.disabled=false}}}
function closeModal(){$('#maintModal').classList.add('hidden');$('#maintForm').innerHTML=''}
function input(name,label,type='text',value='',required=false){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`}
function select(name,label,opts,value=''){return `<label>${label}<select name="${name}">${opts.map(o=>`<option value="${esc(o[0])}" ${o[0]===value?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`}
function equipmentOptions(selected=''){return equipment.map(e=>[e.asset,`${e.asset} - ${e.name||e.assetName||''}`]).map(o=>`<option value="${esc(o[0])}" ${o[0]===selected?'selected':''}>${esc(o[1])}</option>`).join('')}
function loginDialog(){modal('ĐĂNG NHẬP NEMS',`${input('username','Tài khoản','text','',true)}${input('pin','Mã PIN','password','',true)}<button class="primary-btn" type="submit">ĐĂNG NHẬP</button>`,async f=>{const j=await api('login',{username:f.get('username'),pin:f.get('pin')});session=j.session;localStorage.setItem('nemsMaintSession',JSON.stringify(session));updateRoleUI();await refreshAll()})}
function logout(show){session=null;localStorage.removeItem('nemsMaintSession');plans=[];workorders=[];mhistory=[];users=[];updateRoleUI();renderAll();if(show)toast('Đã đăng xuất')}
async function refreshAll(){const j=await api('bootstrap');plans=j.plans||[];workorders=j.workorders||[];mhistory=j.history||[];users=j.users||[];renderAll()}
function computedStatus(p){if(p.actualEnd)return 'completed';if(p.actualStart)return 'in-progress';const today=new Date().toISOString().slice(0,10);if(p.planEnd&&p.planEnd<today)return 'overdue';return p.status||'planned'}
const statusLabel=s=>({planned:'Có kế hoạch','in-progress':'Đang thực hiện',overdue:'Trễ kế hoạch',completed:'Hoàn thành',cancelled:'Đã hủy',open:'Mở',done:'Hoàn thành',paused:'Tạm dừng'}[s]||s);
const statusClass=s=>s==='completed'||s==='done'?'approved':s==='overdue'?'overdue':s==='in-progress'?'due-soon':'pending';
function renderAll(){renderKpis();renderPlans();renderEquipmentStatus();renderWOs();renderHistory();renderUsers();loadAssetMaintenance()}
function renderKpis(){const c={planned:0,'in-progress':0,overdue:0,completed:0};plans.forEach(p=>c[computedStatus(p)]++);const noPlan=equipment.filter(e=>!plans.some(p=>p.asset===e.asset)).length;$('#maintKpis').innerHTML=[['Có kế hoạch',c.planned],['Đang thực hiện',c['in-progress']],['Trễ kế hoạch',c.overdue],['Hoàn thành',c.completed],['Chưa có kế hoạch',noPlan]].map(x=>`<article><b>${x[1]}</b><span>${x[0]}</span></article>`).join('')}
function renderPlans(){const q=($('#planSearch')?.value||'').toLowerCase(),sf=$('#planStatusFilter')?.value||'';const rows=plans.filter(p=>(!sf||computedStatus(p)===sf)&&(!q||JSON.stringify(p).toLowerCase().includes(q)));$('#planCount').textContent=`${rows.length} kế hoạch`;$('#planBody').innerHTML=rows.map(p=>{const s=computedStatus(p);return `<tr><td><b>${esc(p.planId)}</b></td><td>${esc(p.asset)}<br>${esc(p.equipmentName||'')}</td><td>${fmt(p.planStart)} → ${fmt(p.planEnd)}</td><td>${fmt(p.actualStart)} → ${fmt(p.actualEnd)}</td><td>${esc(p.pic||'—')}</td><td><span class="status ${statusClass(s)}">${statusLabel(s)}</span></td><td>${canEdit()?`<button class="mini-action" data-edit-plan="${esc(p.planId)}">Sửa</button> ${isAdmin()?`<button class="mini-action danger" data-del-plan="${esc(p.planId)}">Xóa</button>`:''}`:'—'}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Chưa có dữ liệu hoặc chưa đăng nhập.</td></tr>';$$('[data-edit-plan]').forEach(b=>b.onclick=()=>planDialog(plans.find(x=>x.planId===b.dataset.editPlan)));$$('[data-del-plan]').forEach(b=>b.onclick=()=>remove('deletePlan',{planId:b.dataset.delPlan}))}
function renderEquipmentStatus(){const rows=equipment.map(e=>{const ps=plans.filter(p=>p.asset===e.asset).sort((a,b)=>(a.planStart||'').localeCompare(b.planStart||''));let p=ps.find(x=>['overdue','in-progress'].includes(computedStatus(x)))||ps.find(x=>computedStatus(x)==='planned')||ps.at(-1);let s=p?computedStatus(p):'none';return {e,p,s}});$('#equipmentPlanBody').innerHTML=rows.map(({e,p,s})=>`<tr><td><b>${esc(e.name||e.assetName)}</b></td><td>${esc(e.asset)}</td><td>${esc(e.position||'—')}</td><td>${p?`${fmt(p.planStart)} → ${fmt(p.planEnd)}`:'—'}</td><td><span class="status ${s==='none'?'nodata':statusClass(s)}">${s==='none'?'Chưa có kế hoạch':statusLabel(s)}</span></td><td>${canEdit()?`<button class="mini-action" data-new-asset="${esc(e.asset)}">Tạo kế hoạch</button>`:'—'}</td></tr>`).join('');$$('[data-new-asset]').forEach(b=>b.onclick=()=>planDialog({asset:b.dataset.newAsset}))}
function renderWOs(){$('#woCount').textContent=`${workorders.length} Work Orders`;$('#woBody').innerHTML=workorders.map(w=>`<tr><td><b>${esc(w.woId)}</b></td><td>${esc(w.planId||'—')}</td><td>${esc(w.asset)}</td><td>${esc(w.task||'')}</td><td>${esc(w.assignee||'—')}</td><td>${esc(w.progress||0)}%</td><td><span class="status ${statusClass(w.status)}">${statusLabel(w.status)}</span></td><td>${canEdit()?`<button class="mini-action" data-edit-wo="${esc(w.woId)}">Sửa</button> ${isAdmin()?`<button class="mini-action danger" data-del-wo="${esc(w.woId)}">Xóa</button>`:''}`:'—'}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">Chưa có Work Order.</td></tr>';$$('[data-edit-wo]').forEach(b=>b.onclick=()=>woDialog(workorders.find(x=>x.woId===b.dataset.editWo)));$$('[data-del-wo]').forEach(b=>b.onclick=()=>remove('deleteWorkOrder',{woId:b.dataset.delWo}))}
function renderHistory(){$('#mhCount').textContent=`${mhistory.length} bản ghi`;$('#mhBody').innerHTML=mhistory.map(h=>`<tr><td>${fmt(h.date)}</td><td>${esc(h.asset)}</td><td>${esc(h.woId||'—')}</td><td>${esc(h.description||'')}</td><td>${esc(h.result||'')}</td><td>${esc(h.technician||'—')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Chưa có lịch sử bảo trì trực tuyến.</td></tr>'}
function renderUsers(){if(!isAdmin())return;$('#userBody').innerHTML=users.map(u=>`<tr><td><b>${esc(u.username)}</b></td><td>${esc(u.fullName)}</td><td>${esc(u.role)}</td><td>${u.active?'Đang hoạt động':'Đã khóa'}</td><td><button class="mini-action" data-edit-user="${esc(u.username)}">Sửa</button></td></tr>`).join('');$$('[data-edit-user]').forEach(b=>b.onclick=()=>userDialog(users.find(x=>x.username===b.dataset.editUser)))}
function planDialog(p={}){if(!canEdit())return alert('Bạn không có quyền chỉnh sửa.');modal(p.planId?'SỬA KẾ HOẠCH':'TẠO KẾ HOẠCH',`<input type="hidden" name="planId" value="${esc(p.planId||'')}"><label>Thiết bị<select name="asset" required><option value="">-- Chọn thiết bị --</option>${equipmentOptions(p.asset)}</select></label><div class="form-grid">${input('planStart','Ngày kế hoạch bắt đầu','date',p.planStart||'',true)}${input('planEnd','Ngày kế hoạch kết thúc','date',p.planEnd||'',true)}${input('actualStart','Ngày thực tế bắt đầu','date',p.actualStart||'')}${input('actualEnd','Ngày thực tế kết thúc','date',p.actualEnd||'')}</div>${input('pic','Người phụ trách','text',p.pic||'')}<label>Ghi chú<textarea name="note">${esc(p.note||'')}</textarea></label><button class="primary-btn" type="submit">LƯU KẾ HOẠCH</button>`,async f=>{const asset=f.get('asset'),e=equipment.find(x=>x.asset===asset)||{};await api('savePlan',{plan:{planId:f.get('planId'),asset,equipmentName:e.name||e.assetName||'',position:e.position||'',planStart:f.get('planStart'),planEnd:f.get('planEnd'),actualStart:f.get('actualStart'),actualEnd:f.get('actualEnd'),pic:f.get('pic'),note:f.get('note')}});await refreshAll()})}
function woDialog(w={}){if(!canEdit())return;modal(w.woId?'SỬA WORK ORDER':'TẠO WORK ORDER',`<input type="hidden" name="woId" value="${esc(w.woId||'')}">${select('planId','Kế hoạch',[['','Không liên kết'],...plans.map(p=>[p.planId,`${p.planId} - ${p.asset}`])],w.planId||'')}<label>Thiết bị<select name="asset" required><option value="">-- Chọn --</option>${equipmentOptions(w.asset)}</select></label><label>Công việc<textarea name="task" required>${esc(w.task||'')}</textarea></label>${input('assignee','Người thực hiện','text',w.assignee||'')}${input('progress','Tiến độ (%)','number',w.progress||0)}${select('status','Trạng thái',[['open','Mở'],['in-progress','Đang thực hiện'],['paused','Tạm dừng'],['done','Hoàn thành']],w.status||'open')}<button class="primary-btn" type="submit">LƯU WORK ORDER</button>`,async f=>{await api('saveWorkOrder',{workorder:Object.fromEntries(f.entries())});await refreshAll()})}
function historyDialog(){if(!canEdit())return;modal('GHI NHẬN LỊCH SỬ BẢO TRÌ',`${input('date','Ngày thực hiện','date',new Date().toISOString().slice(0,10),true)}<label>Thiết bị<select name="asset" required><option value="">-- Chọn --</option>${equipmentOptions()}</select></label>${select('woId','Work Order',[['','Không liên kết'],...workorders.map(w=>[w.woId,`${w.woId} - ${w.asset}`])])}<label>Nội dung<textarea name="description" required></textarea></label><label>Kết quả<textarea name="result"></textarea></label>${input('technician','Người thực hiện','text',session?.fullName||'')}<button class="primary-btn" type="submit">LƯU LỊCH SỬ</button>`,async f=>{await api('saveHistory',{record:Object.fromEntries(f.entries())});await refreshAll()})}
function userDialog(u={}){if(!isAdmin())return;modal(u.username?'SỬA NGƯỜI DÙNG':'TẠO NGƯỜI DÙNG',`${input('username','Tài khoản','text',u.username||'',true)}${input('fullName','Họ tên','text',u.fullName||'',true)}${input('pin','Mã PIN mới (để trống nếu giữ nguyên)','password','')}${select('role','Vai trò',[['admin','Admin'],['technician','Technician'],['viewer','Viewer']],u.role||'viewer')}${select('active','Trạng thái',[['true','Hoạt động'],['false','Khóa']],String(u.active!==false))}<button class="primary-btn" type="submit">LƯU NGƯỜI DÙNG</button>`,async f=>{await api('saveUser',{user:Object.fromEntries(f.entries())});await refreshAll()})}
async function remove(action,payload){if(!confirm('Bạn chắc chắn muốn xóa?'))return;try{await api(action,payload);await refreshAll()}catch(e){alert(e.message)}}
function canEdit(){return ['admin','technician'].includes(session?.role)}function isAdmin(){return session?.role==='admin'}
function loadAssetMaintenance(){const asset=$('#detailAsset')?.textContent?.trim();const box=$('#assetMaintenance');if(!box||!asset||!session)return;const ps=plans.filter(p=>p.asset===asset),ws=workorders.filter(w=>w.asset===asset),hs=mhistory.filter(h=>h.asset===asset);box.innerHTML=`<h3>Kế hoạch (${ps.length})</h3>${ps.map(p=>`<div class="event"><b>${esc(p.planId)}</b> · ${fmt(p.planStart)} → ${fmt(p.planEnd)} · ${statusLabel(computedStatus(p))}</div>`).join('')||'<div class="empty">Chưa có kế hoạch.</div>'}<h3>Work Orders (${ws.length})</h3>${ws.map(w=>`<div class="event"><b>${esc(w.woId)}</b> · ${esc(w.task)} · ${esc(w.progress)}%</div>`).join('')||'<div class="empty">Chưa có Work Order.</div>'}<h3>Lịch sử online (${hs.length})</h3>${hs.map(h=>`<div class="event"><b>${fmt(h.date)}</b> · ${esc(h.description)} · ${esc(h.result)}</div>`).join('')||'<div class="empty">Chưa có lịch sử.</div>'}`}
function toast(t){console.log(t);alert(t)}
})();
